// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOh3WUEPxUAtY6oVJqV4Ok1S5aiBDWOh0',
    appId: '1:961270380068:web:d6ffa6db5fd8d9c3fdcab1',
    messagingSenderId: '961270380068',
    projectId: 'qlsv-29e99',
    authDomain: 'qlsv-29e99.firebaseapp.com',
    storageBucket: 'qlsv-29e99.firebasestorage.app',
    measurementId: 'G-4SP9M7ZYEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbt6ktEEA89rwjwFPr2Eol3L_nEak8nZs',
    appId: '1:961270380068:android:6ba4dc97b62944cffdcab1',
    messagingSenderId: '961270380068',
    projectId: 'qlsv-29e99',
    storageBucket: 'qlsv-29e99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKSG_3cbA9FbreKexqpIt_0VE6ayozaI',
    appId: '1:961270380068:ios:9fb710b20293ebc5fdcab1',
    messagingSenderId: '961270380068',
    projectId: 'qlsv-29e99',
    storageBucket: 'qlsv-29e99.firebasestorage.app',
    iosBundleId: 'com.example.qlsv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKSG_3cbA9FbreKexqpIt_0VE6ayozaI',
    appId: '1:961270380068:ios:9fb710b20293ebc5fdcab1',
    messagingSenderId: '961270380068',
    projectId: 'qlsv-29e99',
    storageBucket: 'qlsv-29e99.firebasestorage.app',
    iosBundleId: 'com.example.qlsv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOh3WUEPxUAtY6oVJqV4Ok1S5aiBDWOh0',
    appId: '1:961270380068:web:8d17c455c7fa57a3fdcab1',
    messagingSenderId: '961270380068',
    projectId: 'qlsv-29e99',
    authDomain: 'qlsv-29e99.firebaseapp.com',
    storageBucket: 'qlsv-29e99.firebasestorage.app',
    measurementId: 'G-89062GKTY2',
  );
}
